[theme]
# Azul Marino para botones, sliders y destacados
primaryColor = "#1B396A" 

# Gris muy claro para el fondo principal
backgroundColor = "#F8F9F9" 

# Azul Marino para la barra lateral y tarjetas (segundo plano)
secondaryBackgroundColor = "#1B396A" 

# Color de texto (Negro/Gris oscuro para el fondo claro)
textColor = "#262730"

# Fuente profesional
font = "sans serif"